-- Corrective migration: reshape the legacy reminders table (originally
-- auto-generated by TypeORM with camelCase FK and a now-unused `type`/`sent`
-- pair) to match the current entity definitions, and create the missing
-- reminder_logs table.
--
-- Safe to re-run: all ops are guarded with IF EXISTS / IF NOT EXISTS.

BEGIN;

-- --------------------------------------------
-- 1. reminders: rename legacy columns / drop obsolete ones
-- --------------------------------------------

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema='public' AND table_name='reminders'
             AND column_name='id') THEN
    ALTER TABLE reminders RENAME COLUMN id TO reminder_id;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema='public' AND table_name='reminders'
             AND column_name='hearingHearingId') THEN
    ALTER TABLE reminders RENAME COLUMN "hearingHearingId" TO hearing_id;
  END IF;
END $$;

ALTER TABLE reminders
  ALTER COLUMN reminder_date TYPE timestamp USING reminder_date::timestamp;

ALTER TABLE reminders DROP COLUMN IF EXISTS type;
ALTER TABLE reminders DROP COLUMN IF EXISTS sent;

ALTER TABLE reminders
  ADD COLUMN IF NOT EXISTS is_sent boolean DEFAULT false;

ALTER TABLE reminders
  ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE reminders
  ALTER COLUMN hearing_id SET NOT NULL,
  ALTER COLUMN reminder_date SET NOT NULL;

-- UNIQUE hearing_id so each hearing has at most one reminder
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reminders_hearing_id_key') THEN
    ALTER TABLE reminders
      ADD CONSTRAINT reminders_hearing_id_key UNIQUE (hearing_id);
  END IF;
END $$;

-- Ensure FK is named/behaving consistently with the entity
DO $$
DECLARE cname text;
BEGIN
  SELECT conname INTO cname
  FROM pg_constraint
  WHERE conrelid = 'public.reminders'::regclass AND contype = 'f';

  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE reminders DROP CONSTRAINT %I', cname);
  END IF;
END $$;

ALTER TABLE reminders
  ADD CONSTRAINT reminders_hearing_fkey
  FOREIGN KEY (hearing_id) REFERENCES hearings(hearing_id) ON DELETE CASCADE;

-- --------------------------------------------
-- 2. reminder_logs: create audit table if missing
-- --------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reminder_logs_channel_enum') THEN
    CREATE TYPE reminder_logs_channel_enum AS ENUM ('EMAIL', 'WHATSAPP', 'SMS');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reminder_logs_status_enum') THEN
    CREATE TYPE reminder_logs_status_enum AS ENUM ('PENDING', 'SENT', 'FAILED');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS reminder_logs (
  log_id serial PRIMARY KEY,
  hearing_id int NOT NULL,
  client_id int NOT NULL,
  channel reminder_logs_channel_enum NOT NULL,
  status reminder_logs_status_enum NOT NULL,
  error_message text NULL,
  provider_name text NULL,
  provider_message_id text NULL,
  provider_event_type text NULL,
  provider_last_event_at timestamp NULL,
  sent_at timestamp NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT reminder_logs_hearing_fkey
    FOREIGN KEY (hearing_id) REFERENCES hearings(hearing_id) ON DELETE CASCADE,
  CONSTRAINT reminder_logs_client_fkey
    FOREIGN KEY (client_id) REFERENCES clients(client_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reminder_logs_hearing_id ON reminder_logs (hearing_id);
CREATE INDEX IF NOT EXISTS idx_reminder_logs_client_id ON reminder_logs (client_id);
CREATE INDEX IF NOT EXISTS idx_reminder_logs_provider_message_id ON reminder_logs(provider_message_id);

COMMIT;
